export const SIGNIN = "SIGNIN";
export const SIGNUP = `SIGNUP`;
export const SIGNOUT = `SIGNOUT`;
export const ALLUSERS = `ALLUSERS`;

export const FAMILY_MEMBERS = `FAMILY_MEMBERS`;
export const INVITE_MEMBERS = `INVITE_MEMBERS`;

export const COMMUNITY_RESIDENTS = "COMMUNITY_RESIDENTS";
export const RESIDENTS_ERROR = "RESIDENTS_ERROR";

export const ADD_DOCUMENT_SUCCESS = "ADD_DOCUMENT_SUCCESS";
export const ADD_DOCUMENT_ERROR = "ADD_DOCUMENT_ERROR";

export const GET_DOCUMENT_SUCCESS = "GET_DOCUMENT_SUCCESS";
export const GET_DOCUMENT_ERROR = "GET_DOCUMENT_ERROR";

export const DELETE_DOCUMENT_SUCCESS = "DELETE_DOCUMENT_SUCCESS";
export const DELETE_DOCUMENT_ERROR = "DELETE_DOCUMENT_ERROR";

export const UPDATE_DOCUMENT_SUCCESS = "UPDATE_DOCUMENT_SUCCESS";
export const UPDATE_DOCUMENT_ERROR = "UPDATE_DOCUMENT_ERROR";

export const DOCUMENT_TYPE_SUCCESS = "DOCUMENT_TYPE_SUCCESS";
export const DOCUMENT_TYPE_ERROR = "DOCUMENT_TYPE_ERROR";

export const GET_MEMBER_SUCCESS = "GET_MEMBER_SUCCESS";
export const GET_MEMBER_ERROR = "GET_MEMBER_ERROR";

export const INVITATION_CODE = "INVITATION_CODE";
export const SEND_INVITES_SUCCESS = "SEND_INVITES_SUCCESS";
export const SEND_INVITES_ERROR = "SEND_INVITES_ERROR";

export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_ERROR = "GET_ROLES_ERROR";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";

export const EMAILVERIFICATIONSTATUS = "EMAILVERIFICATIONSTATUS";

export const GET_EXTERNAL_MEMBER_SUCCESS = "GET_EXTERNAL_MEMBER_SUCCESS";
export const GET_EXTERNAL_MEMBER_ERROR = "GET_EXTERNAL_MEMBER_ERROR";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const FEEDBACK_SUCCESS = "FEEDBACK_SUCCESS";
export const FEEDBACK_ERROR = "FEEDBACK_ERROR";

export const GET_AVATAR_SUCCESS = "GET_AVATAR_SUCCESS";
export const GET_AVATAR_ERROR = "GET_AVATAR_ERROR";

export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_ERROR = "UPDATE_AVATAR_ERROR";

export const GET_COMMUNITY_SUCCESS = "GET_COMMUNITY_SUCCESS";
export const GET_COMMUNITY_ERROR = "GET_COMMUNITY_ERROR";
