export const SIGNIN = "SIGNIN";
export const SIGNUP = `SIGNUP`;
export const SIGNOUT = `SIGNOUT`;
export const ALLUSERS = `ALLUSERS`;

export const FAMILY_MEMBERS = `FAMILY_MEMBERS`;
export const INVITE_MEMBERS = `INVITE_MEMBERS`;

export const COMMUNITY_RESIDENTS = "COMMUNITY_RESIDENTS";
export const RESIDENTS_ERROR = "RESIDENTS_ERROR";

export const ADD_DOCUMENT_SUCCESS = "ADD_DOCUMENT_SUCCESS";
export const ADD_DOCUMENT_ERROR = "ADD_DOCUMENT_ERROR";

export const GET_DOCUMENT_SUCCESS = "GET_DOCUMENT_SUCCESS";
export const GET_DOCUMENT_ERROR = "GET_DOCUMENT_ERROR";
